image:
  repository: ghcr.io/rdlucas2/jobregator-notifier
  tag: latest

service:
  port: 8080

probesEnabled: false

env:
  - name: NATS_URL
    value: "nats://nats:4222"
  - name: FIT_SCORE_THRESHOLD
    value: "0.7"
  - name: DISCORD_WEBHOOK_URL
    valueFrom:
      secretKeyRef:
        name: jobregator-secrets
        key: DISCORD_WEBHOOK_URL
